### ISSUE TITLE
Type is not revealed

### ISSUE THREAD

**Issue by JesusTheHun** [NWYLZW/idea-comment-queries#2]
Hello,

Thank you for the initiative of this plugin !

I'm using IntelliJ and there is no output at all: 

```ts
// Nothing shows up
type T = 'hello';
//   ^?

// another try, still nothing
//   v?
type T = 'hello';
```

There is no error, nothing happens.

IntelliJ: `Build #IU-232.9921.47, built on September 12, 2023`
Comment Queries: `2.0.8`

**Comment by NWYLZW** [comment]
Can you provide me with your typescript version?
<img width="316" alt="image" src="https://github.com/NWYLZW/idea-comment-queries/assets/51358815/c4c17407-79a4-4bbd-9349-924afc085ea1">
<img width="509" alt="image" src="https://github.com/NWYLZW/idea-comment-queries/assets/51358815/6ed6f4b8-0570-46ef-947e-df6792fc8dbd">

It may be that IDEA has transformed the TypeScript service in a newer version. They recently sent me an email.

**Comment by JesusTheHun** [comment]
I'm using TypeScript `5.0.4`. But not the bundled one, the one installed on the project.

```
IntelliJ IDEA 2023.2.2 (Ultimate Edition)
Build #IU-232.9921.47, built on September 12, 2023
Runtime version: 17.0.8+7-b1000.22 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 14.0
GC: G1 Young Generation, G1 Old Generation
Memory: 4096M
Cores: 12
Metal Rendering is ON
Kotlin: 232-1.9.0-IJ9921.47
```

**Comment by NWYLZW** [comment]
You can have a try.

https://github.com/NWYLZW/idea-comment-queries/releases/tag/2.1.1

**Comment by JesusTheHun** [comment]
I can't try : `Incompatible: requires IDE build 232.* or earlier` 😅

**Comment by NWYLZW** [comment]
Ah, because of the changes they made to this unstable API `inlayhintsprovider`, I have to upgrade to resolve this issue. Can you upgrade your IDE version as well? This version is relatively stable now. If not, I'll find some time to see if I can migrate the support to a lower version for you.
😮‍💨

**Comment by JesusTheHun** [comment]
Version `2.1.1` is not available for update yet. Once it's available I will update.

I'm currently using :

```
IntelliJ IDEA 2023.3.2 (Ultimate Edition)
Build #IU-233.13135.103, built on December 20, 2023
```

**Comment by JesusTheHun** [comment]
it works !
